name: vocab_app
description: "Your personal vocab friend"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  firebase_core: ^2.25.4
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  path_provider: ^2.1.2
  stack_trace: ^1.11.1
  intl: ^0.18.1
  cloud_firestore: ^4.15.5
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  rxdart: ^0.27.7
  dio: ^5.4.1
  uuid: ^4.3.3
  image_gallery_saver: ^2.0.3
  firebase_auth: ^4.17.5
  firebase_storage: ^11.6.6
  meta: ^1.11.0
  image_picker_platform_interface: ^2.9.4
  image_picker_android: ^0.8.9+3
  http: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  audioplayers: ^5.2.1
  permission_handler: ^11.3.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/vocab_app-logo2.png"
  image_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/locale/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
