name: vocab_app
description: "Your personal vocab friend"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  firebase_core: ^2.25.4
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  stack_trace: ^1.11.1
  intl: ^0.18.1
  cloud_firestore: ^4.15.5
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  rxdart: ^0.27.7
  dio: ^5.4.1
  uuid: ^4.3.3
  image_gallery_saver: ^2.0.3
  firebase_auth: ^4.17.5
  firebase_storage: ^11.6.6
  image_picker_platform_interface: ^2.9.4
  image_picker_android: ^0.8.9+3
  http: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  audioplayers: ^6.0.0
  permission_handler: ^11.3.0
  google_sign_in: ^6.2.1
  flutter_sound: ^9.4.6
  flutter_cache_manager: ^3.3.2
  bloc_test: ^9.1.7
  google_generative_ai: ^0.4.0

# flutter_launcher_icons:
#   android: "flutter_launcher_icon"
#   image_path: "assets/images/vocabular-logo.png"
#   image_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

dependency_overrides:
  flutter_sound: 9.4.6
  flutter_sound_platform_interface: 9.4.6
  flutter_sound_web: 9.4.6
  intl: 0.18.1
  leak_tracker: 10.0.0
  leak_tracker_flutter_testing: 2.0.1
  leak_tracker_testing: 2.0.1
  material_color_utilities: 0.8.0
  meta: 1.11.0
  test_api: 0.6.1
  vm_service: 13.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/locale/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
