// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8sqm0snh6x2J_IIxbQcaBkx63TzG3XA',
    appId: '1:920759037359:android:9b4f57657a9edc84fe935a',
    messagingSenderId: '920759037359',
    projectId: 'blackworks-educational',
    storageBucket: 'blackworks-educational.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI7RfKwfMXXODKSPiuxjdZ4hO3aOe1YGQ',
    appId: '1:920759037359:ios:cb7601b41ac2bf7afe935a',
    messagingSenderId: '920759037359',
    projectId: 'blackworks-educational',
    storageBucket: 'blackworks-educational.appspot.com',
    androidClientId: '920759037359-ng7dpcfpvea83o128aqsc2fi67mvlcmb.apps.googleusercontent.com',
    iosClientId: '920759037359-oapri2vbv0hlqvv30ona43t8q0ki0jjs.apps.googleusercontent.com',
    iosBundleId: 'za.co.blackworks.vocabApp',
  );
}
